name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/k8s_final:latest .
      
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Push Docker image
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/k8s_final:latest ghcr.io/${{ github.repository_owner }}/k8s_final:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/k8s_final:latest
          docker push ghcr.io/${{ github.repository_owner }}/k8s_final:${{ github.sha }}
          docker logout ghcr.io