apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
  labels:
    app: hello-world
spec:
  containers:
  - name: hello-world-container
    image: ghcr.io/shirannimni/k8s_final:latest
    ports:
    - containerPort: 3000